package com.proyecto.retail.Infraestructura;

public class SqlQueries {
	
	public String consultasolicitud = "SELECT asset.id, comp.name as companydescription, age.name as agencydescripcion,"
			+ " dep.name as derparmentdescription,cat.name as type, sta.name as state, tipo.name as priority"
			+ " FROM assetrequests as asset"
			+ " JOIN catalog as cat on asset.catalogid = cat.id"
			+ " JOIN agencies as age on asset.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ " JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ " JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ " JOIN processstates as sta on asset.processstateid = sta.id"
			+ " WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ " AND asset.useridrequested = Coalesce(?, asset.useridrequested) "
			+ " AND asset.catalogid = Coalesce(?, asset.catalogid)"
			+ " AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.processstateid = Coalesce(?, asset.processstateid)";
	
	public String consultaSolicitudSoporte = "SELECT tmp.useridrequested,tmp.id, tmp.companydescription, tmp.agencydescripcion, tmp.derparmentdescription,"
			+ "	tmp.type, tmp.state, tmp.priority, tmp.processstateid FROM (" 
			+ " SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, dep.name as derparmentdescription,"
			+ "	cat.name as type, sta.name as state, tipo.name as priority, asset.processstateid"
			+ " FROM assetrequests as asset"
			+ " JOIN catalog as cat on asset.catalogid = cat.id"
			+ " JOIN agencies as age on asset.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ " JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ " JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ " JOIN processstates as sta on asset.processstateid = sta.id"
			+ " WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ " AND asset.catalogid = Coalesce(?, asset.catalogid) "
			+ " AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.processstateid = (select id from processstates where code = 'INGRESADO' limit 1)"
			+ " UNION"
			+ " SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, dep.name as derparmentdescription,"
			+ "	cat.name as type, sta.name as state, tipo.name as priority, asset.processstateid "
			+ " FROM assetrequests as asset"
			+ " JOIN catalog as cat on asset.catalogid = cat.id"
			+ " JOIN agencies as age on asset.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ " JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ " JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ " JOIN processstates as sta on asset.processstateid = sta.id"
			+ " WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ " AND asset.useridassigned = Coalesce(?, asset.useridrequested) "
			+ " AND asset.catalogid = Coalesce(?, asset.catalogid) "
			+ " AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.processstateid in(select id from processstates where code in('PENDIENTE','APROBADO','RECHAZADO'))) as tmp"
			+ " WHERE tmp.processstateid = Coalesce(?, tmp.processstateid);";
	
	public String consultaSolicitudBodega = "SELECT tmp.useridrequested,tmp.id, tmp.inventoryproductid, tmp.companydescription, tmp.agencydescripcion, "
			+ " tmp.derparmentdescription,tmp.type, tmp.state, tmp.priority, tmp.processstateid, tmp.codenameproduct FROM ("
			+ "	SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, "
			+ "	dep.name as derparmentdescription, cat.name as type, sta.name as state, tipo.name as priority, asset.processstateid,"
			+ "	invprod.id as inventoryproductid, lpad(CAST(invprod.id AS TEXT), 12, '0') || '-' || catprod.name as codenameproduct"
			+ "	FROM assetrequests as asset"
			+ "	JOIN inventoryproducts as invprod on invprod.id = asset.inventoryproductid"
			+ "	JOIN products as prod on prod.id = invprod.productid"
			+ "	JOIN catalog as catprod on catprod.id = prod.catalogproductid"
			+ "	JOIN catalog as cat on asset.catalogid = cat.id"
			+ "	JOIN agencies as age on asset.agencyid = age.id"
			+ "	JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ "	JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ "	JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ "	JOIN processstates as sta on asset.processstateid = sta.id"
			+ "	WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ "	AND asset.agencyid = Coalesce(?, asset.agencyid) "
			+ "	AND asset.catalogid = Coalesce(?, asset.catalogid) "
			+ "	AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ "	AND asset.processstateid in(select id from processstates "
			+ " WHERE code in( 'BODEGA', 'MANTENIMIENTO', 'BAJA', 'DEVOLUCION'))) as tmp"
			+ " WHERE tmp.processstateid = Coalesce(?, tmp.processstateid)";
	
	public String consultaSolicitudVentas = "SELECT tmp.useridrequested,tmp.id, tmp.companydescription, tmp.agencydescripcion, tmp.derparmentdescription,"
			+ "	tmp.type, tmp.state, tmp.priority, tmp.processstateid FROM ("
			+ " SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, dep.name as derparmentdescription,"
			+ "	cat.name as type, sta.name as state, tipo.name as priority, asset.processstateid "
			+ " FROM assetrequests as asset"
			+ " JOIN catalog as cat on asset.catalogid = cat.id"
			+ " JOIN agencies as age on asset.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ " JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ " JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ " JOIN processstates as sta on asset.processstateid = sta.id"
			+ " WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ " AND asset.agencyid = Coalesce(?, asset.agencyid) "
			+ " AND asset.catalogid = Coalesce(?, asset.catalogid) "
			+ " AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.processstateid in(select id from processstates where code in( 'APROBADO','ENVIO_PROFORMA','PROFORMA_APROBADA', 'PROFORMA_RECHAZADA', 'GUIA_REMISION'))) as tmp"
			+ " WHERE tmp.processstateid = Coalesce(?, tmp.processstateid)";
	
	public String consultaSolicitudGerencia = "SELECT tmp.useridrequested,tmp.id, tmp.companydescription, tmp.agencydescripcion, tmp.derparmentdescription,"
			+ "	tmp.type, tmp.state, tmp.priority, tmp.processstateid FROM ("
			+ " SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, dep.name as derparmentdescription,"
			+ "	cat.name as type, sta.name as state, tipo.name as priority, asset.processstateid "
			+ " FROM assetrequests as asset"
			+ " JOIN catalog as cat on asset.catalogid = cat.id"
			+ " JOIN agencies as age on asset.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ " JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ " JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ " JOIN processstates as sta on asset.processstateid = sta.id"
			+ " WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ " AND asset.agencyid = Coalesce(?, asset.agencyid) "
			+ " AND asset.catalogid = Coalesce(?, asset.catalogid) "
			+ " AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.processstateid in(select id from processstates where code in( 'ENVIO_PROFORMA','PROFORMA_APROBADA','PROFORMA_RECHAZADA', 'DESPACHADO', 'DEVOLUCION', 'RECIBIDO'))) as tmp"
			+ " WHERE tmp.processstateid = Coalesce(?, tmp.processstateid)";
	
	public String consultaSolicitudInventario = "SELECT tmp.useridrequested,tmp.id, tmp.companydescription, tmp.agencydescripcion, tmp.derparmentdescription,"
			+ "	tmp.type, tmp.state, tmp.priority, tmp.processstateid, tmp.numberguide FROM ("
			+ "	SELECT asset.useridrequested,asset.id, comp.name as companydescription, age.name as agencydescripcion, "
			+ "		dep.name as derparmentdescription, cat.name as type, sta.name as state, tipo.name as priority, "
			+ "		asset.processstateid, asset.numberguide"
			+ "	FROM assetrequests as asset"
			+ "	JOIN catalog as cat on asset.catalogid = cat.id"
			+ "	JOIN agencies as age on asset.agencyid = age.id"
			+ "	JOIN companytobebilling as comp ON asset.billingid = comp.id"
			+ "	JOIN workdepartments as dep on asset.workdepartmentid = dep.id"
			+ "	JOIN catalog as tipo on asset.prioritytypeid = tipo.id"
			+ "	JOIN processstates as sta on asset.processstateid = sta.id"
			+ "	WHERE asset.datecreate BETWEEN TO_TIMESTAMP(?, 'YYYY-MM-DD') AND TO_TIMESTAMP(?, 'YYYY-MM-DD')"
			+ "	AND asset.catalogid = Coalesce(?, asset.catalogid)"
			+ "	AND asset.prioritytypeid = Coalesce(?, asset.prioritytypeid)"
			+ " AND asset.numberguide like CONCAT('%',Coalesce(?, asset.numberguide),'%') "
			+ "	AND asset.processstateid in(select id from processstates where code in('GUIA_REMISION','SALIDA_CD', 'RECIBIDO_CDI', 'DESPACHADO'))) as tmp";
	
	public String reportPorEstados = "SELECT processstateid, proc.name, COUNT(ass.id) as quantity FROM assetrequests as ass"
			+ " JOIN processstates as proc on ass.processstateid = proc.id"
			+ " WHERE DATE_PART('month',ass.datecreate) = Coalesce(?, DATE_PART('month',ass.datecreate))"
			+ " AND DATE_PART('year',ass.datecreate) = Coalesce(?, DATE_PART('year',ass.datecreate))"
			+ " GROUP BY processstateid, proc.name;";
	
	public String reportPorAnios = "SELECT tmp.mes,tmp.mes_desc, "
			+ " MAX(case when (tmp.name='Mantenimiento') then tmp.counttype else NULL end) as Mantenimiento,"
			+ " MAX(case when (tmp.name='Requerimiento') then tmp.counttype else NULL end) as Requerimiento"
			+ " FROM "
			+ " (SELECT TO_CHAR(ass.datecreate, 'Month') AS mes_desc,"
			+ "	DATE_PART('year',ass.datecreate) as anio,"
			+ "	DATE_PART('month',ass.datecreate) as mes,"
			+ "	ass.catalogid,"
			+ "	cat.name,"
			+ "	COUNT(ass.catalogid) as counttype"
			+ " FROM assetrequests as ass"
			+ " JOIN catalog as cat on cat.id = catalogid"
			+ " WHERE DATE_PART('year',ass.datecreate) = Coalesce(?, DATE_PART('year',ass.datecreate))"
			+ " GROUP BY TO_CHAR(ass.datecreate, 'Month'),"
			+ "	DATE_PART('year',ass.datecreate),"
			+ "	DATE_PART('month',ass.datecreate),"
			+ "	catalogid,"
			+ "	cat.name) AS tmp"
			+ " group by tmp.mes_desc,"
			+ "		tmp.mes"
			+ " order by tmp.mes";
	
	public String consultCatalogInventoyProduct = "SELECT invprod.id, cat.id as catalogid, cat.code, cat.name, cat.description,"
			+ " lpad(CAST(invprod.id AS TEXT), 12, '0') as codeproduct"
			+ " FROM inventories as inv"
			+ " JOIN inventoryproducts as invprod on inv.id = invprod.inventoryid"
			+ " JOIN products as prod on prod.id = invprod.productid"
			+ " JOIN catalog as cat on cat.id = prod.catalogproductid"
			+ " JOIN catalog as catest on catest.id = invprod.productstateid"
			+ " WHERE prod.state = true"
			+ " AND invprod.state = true"
			+ " AND invprod.billingid = Coalesce(?, invprod.billingid)"
			+ " AND invprod. workdepartmentid = Coalesce(?, invprod. workdepartmentid)"
			+ " AND invprod.agencyid = Coalesce(?, invprod.agencyid)"
			+ " AND catest.name = 'OPERATIVO'";
	
	public String consultaInventoyProductById = "SELECT invprod.id ,lpad(CAST(invprod.id AS TEXT), 12, '0') as code, cat.name, "
			+ " comp.name as companydescription, age.name as agencydescripcion, dep.name as derparmentdescription"
			+ " FROM inventoryproducts AS invprod "
			+ " JOIN agencies as age on invprod.agencyid = age.id"
			+ " JOIN companytobebilling as comp ON invprod.billingid = comp.id"
			+ " JOIN workdepartments as dep on invprod.workdepartmentid = dep.id "
			+ " JOIN inventories AS inv ON inv.id = invprod.inventoryid"
			+ " JOIN products AS prod ON prod.id = invprod.productid"
			+ " JOIN catalog AS cat ON cat.id = inv.catalogid"
			+ " where invprod.id = ?";
}
